simulation_ignition_ros_control:
  ros__parameters:
    use_sim_time: true

# Separate controller manager used for simulation - only difference is 
# the use_sim_time parameter (it is the easiest way to do it with ign ros2 control)  
simulation_controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 25 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    psd_vehicle_base_controller:
      type: psd_vehicle_base_controller/AckSteeringDiffDrive
    imu_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

controller_manager:
  ros__parameters:
    use_sim_time: false
    update_rate: 25 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    steering_fl_controller:
      type: effort_controllers/JointEffortController
      joint: steering_fl
    steering_fr_controller:
      type: effort_controllers/JointEffortController
      joint: steering_fr

    imu_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

imu_broadcaster:
  ros__parameters:
    sensor_name: "imu"
    frame_id: "imu_link"

